---
name: "Run Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v15
      with:
        nix_path: nixpkgs=channel:nixos-21.05
    - uses: cachix/cachix-action@v10
      with:
        name: edemocracy
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: ./test-setup.sh /tmp
    - run: nix-shell --run pytest


# vim: set filetype=yaml sw=2 ts=2 sts=2 expandtab:
